"""initial mvp schema

Revision ID: 1eb4f1a31f59
Revises:
Create Date: 2026-09-04 10:57:23.572477
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1eb4f1a31f59"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "families",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "family_memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "user_id", name="uq_family_member"),
    )
    op.create_index(op.f("ix_family_memberships_family_id"), "family_memberships", ["family_id"], unique=False)
    op.create_index(op.f("ix_family_memberships_user_id"), "family_memberships", ["user_id"], unique=False)
    op.create_table(
        "patients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("preferred_name", sa.String(length=120), nullable=False),
        sa.Column("legal_name", sa.String(length=160), nullable=True),
        sa.Column("phone_e164", sa.String(length=32), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("preferred_language", sa.String(length=32), nullable=False),
        sa.Column("high_energy_local_time", sa.String(length=5), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_family_id"), "patients", ["family_id"], unique=False)
    op.create_table(
        "call_schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("local_time", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("days_of_week", sa.JSON(), nullable=False),
        sa.Column("quiet_start", sa.String(length=5), nullable=True),
        sa.Column("quiet_end", sa.String(length=5), nullable=True),
        sa.Column("language_code", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("allow_one_retry", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_schedules_patient_id"), "call_schedules", ["patient_id"], unique=True)
    op.create_table(
        "cognitive_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("activity_type", sa.String(length=48), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=True),
        sa.Column("idempotency_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("termination_reason", sa.String(length=48), nullable=True),
        sa.Column("session_score", sa.Float(), nullable=True),
        sa.Column("summary_accuracy", sa.Float(), nullable=True),
        sa.Column("average_response_latency_ms", sa.Float(), nullable=True),
        sa.Column("hesitation_count", sa.Integer(), nullable=False),
        sa.Column("review_classification", sa.String(length=16), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id", "source", "external_id", name="uq_patient_source_external_id"),
    )
    op.create_index(op.f("ix_cognitive_sessions_patient_id"), "cognitive_sessions", ["patient_id"], unique=False)
    op.create_index("ix_sessions_patient_started", "cognitive_sessions", ["patient_id", "started_at"], unique=False)
    op.create_table(
        "family_memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("memory_type", sa.String(length=32), nullable=False),
        sa.Column("subject_name", sa.String(length=120), nullable=True),
        sa.Column("relationship_label", sa.String(length=120), nullable=True),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("accepted_answers", sa.JSON(), nullable=False),
        sa.Column("asset_ref", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("consent_recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_family_memories_patient_id"), "family_memories", ["patient_id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("same_day_enabled", sa.Boolean(), nullable=False),
        sa.Column("routine_enabled", sa.Boolean(), nullable=False),
        sa.Column("caregiver_phone_e164", sa.String(length=32), nullable=True),
        sa.Column("reminders_paused", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("patient_id"),
    )
    op.create_table(
        "patient_devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patient_devices_patient_id"), "patient_devices", ["patient_id"], unique=False)
    op.create_index(op.f("ix_patient_devices_token_hash"), "patient_devices", ["token_hash"], unique=True)
    op.create_table(
        "patient_join_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["family_id"], ["families.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    op.create_index(op.f("ix_patient_join_codes_family_id"), "patient_join_codes", ["family_id"], unique=False)
    op.create_index(op.f("ix_patient_join_codes_patient_id"), "patient_join_codes", ["patient_id"], unique=False)
    op.create_table(
        "alert_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("delivery_status", sa.String(length=24), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["cognitive_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(op.f("ix_alert_events_patient_id"), "alert_events", ["patient_id"], unique=False)
    op.create_index(op.f("ix_alert_events_session_id"), "alert_events", ["session_id"], unique=False)
    op.create_table(
        "session_metrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("client_metric_id", sa.String(length=120), nullable=True),
        sa.Column("idempotency_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("item_type", sa.String(length=64), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("average_response_latency_ms", sa.Float(), nullable=True),
        sa.Column("hesitation_count", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(length=16), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["cognitive_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "client_metric_id", name="uq_session_client_metric"),
    )
    op.create_index("ix_metrics_patient_recorded", "session_metrics", ["patient_id", "recorded_at"], unique=False)
    op.create_index(op.f("ix_session_metrics_patient_id"), "session_metrics", ["patient_id"], unique=False)
    op.create_index(op.f("ix_session_metrics_session_id"), "session_metrics", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_metrics_session_id"), table_name="session_metrics")
    op.drop_index(op.f("ix_session_metrics_patient_id"), table_name="session_metrics")
    op.drop_index("ix_metrics_patient_recorded", table_name="session_metrics")
    op.drop_table("session_metrics")
    op.drop_index(op.f("ix_alert_events_session_id"), table_name="alert_events")
    op.drop_index(op.f("ix_alert_events_patient_id"), table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index(op.f("ix_patient_join_codes_patient_id"), table_name="patient_join_codes")
    op.drop_index(op.f("ix_patient_join_codes_family_id"), table_name="patient_join_codes")
    op.drop_table("patient_join_codes")
    op.drop_index(op.f("ix_patient_devices_token_hash"), table_name="patient_devices")
    op.drop_index(op.f("ix_patient_devices_patient_id"), table_name="patient_devices")
    op.drop_table("patient_devices")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_family_memories_patient_id"), table_name="family_memories")
    op.drop_table("family_memories")
    op.drop_index("ix_sessions_patient_started", table_name="cognitive_sessions")
    op.drop_index(op.f("ix_cognitive_sessions_patient_id"), table_name="cognitive_sessions")
    op.drop_table("cognitive_sessions")
    op.drop_index(op.f("ix_call_schedules_patient_id"), table_name="call_schedules")
    op.drop_table("call_schedules")
    op.drop_index(op.f("ix_patients_family_id"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_family_memberships_user_id"), table_name="family_memberships")
    op.drop_index(op.f("ix_family_memberships_family_id"), table_name="family_memberships")
    op.drop_table("family_memberships")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("families")
    # ### end Alembic commands ###
